# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/19257/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6676-DESKTOP-8J2IQA1/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.cache/wt [current_project]
set_property parent.project_path C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/and_gate.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/carry_lookaheadRevB.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/cla8bit.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/fourbitadder.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/half_adder.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/shift_and_zero.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/xor_gate.v
  C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/sources_1/new/unsigned_int_multiplier.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/constrs_1/new/mult.xdc
set_property used_in_implementation false [get_files C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.srcs/constrs_1/new/mult.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top unsigned_int_multiplier -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef unsigned_int_multiplier.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file unsigned_int_multiplier_utilization_synth.rpt -pb unsigned_int_multiplier_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
