webtalk_init -webtalk_dir C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.sim/sim_1/behav/xsim/xsim.dir/tb_multiplier_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 14 19:16:13 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2db49e7d-ce42-46ca-b2d5-5fea79b56f0f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c1878aed005f44fcaaa5610c6d197b37" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "134" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5984_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3311077631 -regid "" -xml C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.sim/sim_1/behav/xsim/xsim.dir/tb_multiplier_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.sim/sim_1/behav/xsim/xsim.dir/tb_multiplier_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Vivado/unsignedmultiplierLab4Part1/unsignedmultiplierLab4Part1.sim/sim_1/behav/xsim/xsim.dir/tb_multiplier_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
